name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Install dependencies
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Debug

    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln  --configuration Debug --collect:"XPlat Code Coverage"

    - name: Aggregate coverage
      run: reportgenerator -reports:tests/**/coverage.cobertura.xml -targetdir:tests/CoverageReport -reporttypes:HtmlSummary
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: tests/CoverageReport/**
    

